package io.github.phanducquang.ssi.portfolio.model;

public record DerivativePpmmr(
        String accountNo,
        double accountBalance,
        double fee,
        double commission,
        double interest,
        double loan,
        double deliveryAmount,
        double floatingPl,
        double tradingPl,
        double totalPl,
        double marginable,
        double depositable,
        double rcCall,
        double withdrawable,
        double nonCashDrawableRcCall,
        double cashSsi,
        double validNonCashSsi,
        double totalAssetSsi,
        double withdrawableSsi,
        double eeSsi,
        double cashVsdc,
        double validNonCashVsdc,
        double totalAssetVsdc,
        double withdrawableVsdc,
        double eeVsdc,
        double spreadMarginSsi,
        double deliveryMarginSsi,
        double marginReqSsi,
        double accountRatioSsi,
        double usedLimitWarningLevel1Ssi,
        double usedLimitWarningLevel2Ssi,
        double usedLimitWarningLevel3Ssi,
        double marginCallSsi,
        double spreadMarginVsdc,
        double deliveryMarginVsdc,
        double marginReqVsdc,
        double accountRatioVsdc,
        double usedLimitWarningLevel1Vsdc,
        double usedLimitWarningLevel2Vsdc,
        double usedLimitWarningLevel3Vsdc,
        double marginCallVsdc,
        double totalEquity,
        double extInterest) {
}
